export function generatePiScript(opts: {
  assetName: string;
  gatewayToken: string;
  monitorHost: string;
  monitorPort: number;
  monitorUsername: string;
  monitorPassword: string;
  supabaseUrl: string;
  supabaseAnonKey: string;
  intervalMinutes: number;
  serviceUser?: string;
}) {
  const {
    assetName,
    gatewayToken,
    monitorHost,
    monitorPort,
    monitorUsername,
    monitorPassword,
    supabaseUrl,
    supabaseAnonKey,
    intervalMinutes,
    serviceUser = "pi",
  } = opts;

  return `#!/usr/bin/env python3
"""
NM Magnet Monitor -- gateway reporting script
Asset: ${assetName}
Generated by the admin panel -- do not commit this file to a public repo,
it contains this asset's gateway token and the MagMon's local credentials.

WHAT THIS DOES
1. Logs into the MagMon's local web interface (HTTP Basic Auth + cookie/form
   login fallback -- these devices are inconsistent about which one they
   want, so this tries Basic Auth first and falls through to a form login
   if the device demands one).
2. Fetches /goform/showMinutesCGI, which returns a <pre>-wrapped text table.
   Two on-the-wire layouts are known to exist across the fleet and this
   parser auto-detects and handles BOTH:
     - "labeled" header, e.g. Date, Time, HeLvl, H20_Flow, H2O_Temp, ...
     - "legend" header, e.g. Date Time In_01 In_02 ... preceded by lines
       like "Input 01 is He_Level" that map generic column names to real
       ones.
   This parser was validated field-by-field against live fleet devices of
   both generations, not reverse-engineered blind.
3. If the HTTP path fails (after a few quick retries), falls back to pulling
   the same minute data from the daily .dat file over anonymous FTP. The FTP
   daemon is a separate service from the web interface and usually survives a
   webserver crash, so this keeps reporting through the failure that most often
   takes these units offline. FTP readings are stamped source="ftp" in the raw
   payload; HTTP readings are stamped source="http". (FTP yields only the single
   latest row; any minutes missed while HTTP was down self-heal once HTTP
   returns and its hourly table backfills them.)
4. Reports EVERY minute row that is newer than the last one already sent -- not
   just the latest -- to Supabase via report_telemetry_batch, authenticated with
   this asset's gateway token. The HTTP table already contains the last hour of
   one-minute rows, so this yields full minute-resolution history WITHOUT polling
   the MagMon any harder: the poll interval only sets how often we CONTACT the
   device, not the stored resolution. A high-water mark (persisted on disk) and
   an idempotent (asset_id, recorded_at) DB index mean rows are never
   double-stored across overlapping fetches or restarts.

HOW THIS RUNS -- READ THIS FIRST
This script runs CONTINUOUSLY. It has its own internal timer and sleeps
${intervalMinutes} minutes between polls. It is designed to be started ONCE
and left running under systemd.

  *** DO NOT SCHEDULE THIS SCRIPT WITH CRON. ***

Cron does not check whether the previous run finished. Because this script
never exits, a "*/${intervalMinutes} * * * *" cron entry starts a BRAND NEW
copy every ${intervalMinutes} minutes while every earlier copy keeps running.
After a day you have hundreds of copies all polling at once. In August 2026
this filled most of a 500 MB database in about 37 hours and eventually
crashed the Pis. A flock guard below now makes this impossible, but the
correct answer is still systemd, not cron.

SETUP -- ONE ASSET (a single machine can run several of these side by side)
  sudo apt-get install -y python3-requests   # once per machine, not per asset

  sudo install -o ${serviceUser} -g "$(id -gn ${serviceUser})" -m 700 nm-magmon-gateway-${assetName}.py /opt/magmon-gateway-${assetName}.py
  sudo cp nm-magmon-gateway-${assetName}.service /etc/systemd/system/nm-magmon-gateway-${assetName}.service
  sudo systemctl daemon-reload
  sudo systemctl enable --now nm-magmon-gateway-${assetName}

VERIFY IT IS HEALTHY
  sudo journalctl -u nm-magmon-gateway-${assetName} -f     # watch it report
  pgrep -c -f magmon-gateway-${assetName}                  # MUST print 1, never more
  crontab -l                                               # MUST NOT mention magmon

RUNNING SEVERAL ON ONE MACHINE
Each asset has its OWN script (/opt/magmon-gateway-${assetName}.py), its OWN
systemd unit (nm-magmon-gateway-${assetName}.service), its OWN lock file, and
its OWN log identifier (magmon-${assetName}). Nothing is shared, so one server
-- e.g. one reaching several sites over a VPN -- can run any number of them at
once. Just repeat this setup for each asset.

NOTE ON FILE PERMISSIONS
This file contains this asset's gateway token in plain text. Install it owned by
'${serviceUser}' with mode 700 as shown above: the service runs as '${serviceUser}',
so a root-owned mode-700 file would be unreadable and a world-readable one would
leak the token.

If 'requests' is missing at startup, install it system-wide with apt as shown.
A user-level "pip3 install --user" is NOT enough if the service ever runs as a
different user than the one that ran pip.
"""

import os
import re
import sys
import time
import json
import fcntl
import signal
import base64
import socket
import ftplib
import datetime
import traceback
import requests

# --- Fixed per-asset config (do not edit unless re-issued by admin) ---
GATEWAY_TOKEN     = "${gatewayToken}"
SUPABASE_URL      = "${supabaseUrl}"
SUPABASE_ANON_KEY = "${supabaseAnonKey}"

MAGMON_HOST     = "${monitorHost}"
MAGMON_PORT     = ${monitorPort}
MAGMON_USER     = "${monitorUsername}"
MAGMON_PASS     = "${monitorPassword}"
BASE_URL        = f"http://{MAGMON_HOST}:{MAGMON_PORT}"

POLL_INTERVAL_SECONDS = ${intervalMinutes * 60}
# report_telemetry (single row) is kept server-side for compat; this collector
# uses the batch RPC so one cycle can store every new minute row it already
# fetched -- full minute resolution independent of the poll interval.
REPORT_ENDPOINT       = f"{SUPABASE_URL}/rest/v1/rpc/report_telemetry"
BATCH_REPORT_ENDPOINT = f"{SUPABASE_URL}/rest/v1/rpc/report_telemetry_batch"

# High-water mark = the newest DEVICE timestamp already reported, persisted so a
# restart does not re-send the last hour. /var/tmp survives reboots (unlike
# /tmp); if neither is writable we still run -- the DB's unique (asset_id,
# recorded_at) index dedupes any re-send, this file just avoids the extra work.
HWM_CANDIDATES = [
    "/var/tmp/nm-magmon-gateway-${assetName}.hwm",
    "/tmp/nm-magmon-gateway-${assetName}.hwm",
]

# These MagMon controllers run a tiny single-connection GoAhead webserver that
# intermittently refuses connections (Errno 111) when it is briefly busy -- and
# under sustained hammering the HTTP task can wedge entirely until the unit is
# power-cycled. So a single failed connect is NOT a reason to write off the whole
# poll interval: retry a few times with a short backoff within the cycle before
# giving up until the next one. Kept small so a genuinely dead webserver is not
# pounded on.
POLL_RETRIES          = 3
RETRY_BACKOFF_SECONDS = 10

# FTP fallback. The MagMon's CF disk also serves the same minute data as daily
# .dat files over anonymous FTP. This is used ONLY when the HTTP path fails: the
# FTP daemon is a SEPARATE service from the GoAhead webserver, so it commonly
# stays up even when the webserver has wedged (the exact failure that takes these
# units offline). These are the MagMon's fixed anonymous-FTP creds/paths --
# fleet-wide device constants, not per-asset secrets. Readings pulled this way
# are stamped source="ftp" in the reported raw payload so they stay auditable.
FTP_PORT = 21
FTP_USER = "anonymous"
FTP_PASS = "MagnetMonitor"
FTP_DIR  = "CFDISK/mindata"

SESSION = requests.Session()
SESSION.auth = (MAGMON_USER, MAGMON_PASS)
SESSION.headers.update({
    "User-Agent": "NM-MagMon-Gateway/1.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Cache-Control": "no-cache",
})

# ========= Login (only needed if the device rejects Basic Auth alone) =========
LOGIN_ACTION_FALLBACKS = ["/goform/loginCGI", "/goform/ManageLogin", "/goform/login", "/goform/formLogin", "/cgi-bin/login"]
USER_FIELD_CANDIDATES  = ["username", "user", "login", "uname", "name"]
PASS_FIELD_CANDIDATES  = ["password", "pass", "pwd", "key"]

def discover_login_form(html, page_url):
    m_action = re.search(r'(?is)<form[^>]*action=["\\']([^"\\']+)["\\']', html)
    action_url = requests.compat.urljoin(page_url, m_action.group(1)) if m_action else None
    names = re.findall(r'(?is)<input[^>]*name=["\\']([^"\\']+)["\\'][^>]*>', html)
    user_field = pass_field = None
    for nm in names:
        if user_field is None and re.search(r'(user|login|name|uname)', nm, re.I):
            user_field = nm
        if pass_field is None and re.search(r'(pass|pwd|key)', nm, re.I):
            pass_field = nm
    return action_url, user_field or USER_FIELD_CANDIDATES[0], pass_field or PASS_FIELD_CANDIDATES[0]

def try_login(action_url, user_field, pass_field, referer_url):
    if not action_url:
        raise RuntimeError("No login action URL discovered.")
    form = {user_field: MAGMON_USER, pass_field: MAGMON_PASS}
    resp = SESSION.post(action_url, data=form, headers={"Referer": referer_url}, timeout=12)
    if re.search(r"Unknown Username/Password|User not logged in|Access Error", resp.text, re.I):
        raise RuntimeError("Login POST returned failure.")

def login_magmon():
    html, page_used = None, BASE_URL + "/"
    for url in [f"{BASE_URL}/index.html", f"{BASE_URL}/", f"{BASE_URL}/login.html"]:
        try:
            resp = SESSION.get(url, timeout=10)
            html, page_used = resp.text, url
            break
        except Exception:
            continue

    if html:
        try:
            action_url, user_field, pass_field = discover_login_form(html, page_used)
            if action_url:
                try_login(action_url, user_field, pass_field, page_used)
                return
        except Exception:
            pass

    for rel in LOGIN_ACTION_FALLBACKS:
        url = requests.compat.urljoin(BASE_URL, rel)
        for uf in USER_FIELD_CANDIDATES:
            for pf in PASS_FIELD_CANDIDATES:
                try:
                    try_login(url, uf, pf, page_used)
                    return
                except Exception:
                    continue
    raise RuntimeError("All login attempts failed.")

def fetch_minutes_raw_socket(num_hours=1, start_day=0, start_hour=1):
    # Some MagMon units return a response urllib3/http.client can't parse as
    # standard HTTP (BadStatusLine). We work around it with a raw socket request
    # that reads the body directly instead.
    path = f"/goform/showMinutesCGI?num_hours={num_hours}&start_day={start_day}&start_hour={start_hour}"
    basic = base64.b64encode(f"{MAGMON_USER}:{MAGMON_PASS}".encode("ascii")).decode("ascii")
    cookie_parts = [f"{c.name}={c.value}" for c in SESSION.cookies]
    req_lines = [
        f"GET {path} HTTP/1.0",
        f"Host: {MAGMON_HOST}:{MAGMON_PORT}",
        f"Authorization: Basic {basic}",
        "User-Agent: NM-MagMon-Gateway/1.0",
        "Accept: */*",
    ]
    if cookie_parts:
        req_lines.append("Cookie: " + "; ".join(cookie_parts))
    req_lines.append("")
    req_lines.append("")
    req_bytes = "\\r\\n".join(req_lines).encode("ascii", errors="ignore")

    chunks = []
    with socket.create_connection((MAGMON_HOST, MAGMON_PORT), timeout=15) as s:
        s.sendall(req_bytes)
        while True:
            data = s.recv(4096)
            if not data:
                break
            chunks.append(data)
    body_all = b"".join(chunks).decode("latin-1", errors="ignore")
    return re.split(r"\\r?\\n\\r?\\n", body_all, maxsplit=1)[-1]

def fetch_minutes(num_hours=1, start_day=0, start_hour=1):
    url = f"{BASE_URL}/goform/showMinutesCGI?num_hours={num_hours}&start_day={start_day}&start_hour={start_hour}"
    try:
        resp = SESSION.get(url, timeout=20)
        body = resp.text
    except Exception as e:
        print(f"[nm-magmon-gateway] normal fetch failed ({e}); trying raw socket fallback")
        body = fetch_minutes_raw_socket(num_hours, start_day, start_hour)

    if "User not logged in" in body or "Access Error" in body:
        login_magmon()
        try:
            resp = SESSION.get(url, timeout=20)
            body = resp.text
        except Exception:
            body = fetch_minutes_raw_socket(num_hours, start_day, start_hour)
        if "User not logged in" in body or "Access Error" in body:
            raise RuntimeError("Still not logged in after login attempt.")
    return body

# ========= Parser (handles both MagMon on-wire header generations) =========
LABEL_MAP_NORMALIZE = {
    "He_Level": "HeLvl", "HeLevel": "HeLvl", "Helium_Level": "HeLvl", "HeLvl": "HeLvl",
    "Water_Flow": "H20_Flow", "WaterFlow": "H20_Flow", "H20_Flow": "H20_Flow",
    "Water_Temp": "H2O_Temp", "WaterTemp": "H2O_Temp", "Water_Temperature": "H2O_Temp", "H2O_Temp": "H2O_Temp",
    "Shield_Si410": "Shield", "Shield": "Shield",
    "Recon_RuO": "ReconRuO", "ReconRuO": "ReconRuO",
    "Recon_Si410": "ReconSi410", "ReconSi410": "ReconSi410",
    "Coldhead_RuO": "ColdheadRuO", "ColdheadRuO": "ColdheadRuO",
    "He_Pressure": "HePress", "He_Press": "HePress", "HePress": "HePress",
}
ALL_NUMERIC = ["HeLvl", "H20_Flow", "H2O_Temp", "Shield", "ReconRuO", "ReconSi410", "ColdheadRuO",
               "HePress", "CS1", "CDC1", "HT", "HDC", "RF", "FM", "SM", "EC1", "EC2", "EC3", "EC4"]

def _to_float(x):
    try:
        return float(str(x).strip())
    except Exception:
        return None

def _strip_html_keep_pre(text):
    m = re.search(r"(?is)<pre[^>]*>(.*?)</pre>", text)
    content = m.group(1) if m else text
    return re.sub(r"(?is)<[^>]+>", "", content)

def _split(line):
    if "," in line:
        return [c.strip() for c in line.split(",")]
    return re.split(r"[ \\t]+", line.strip())

def _norm_col(name):
    # Fold a raw header/legend column name to its canonical short name.
    # Devices are inconsistent: some emit the short names directly (HeLvl,
    # Shield, HePress), others emit the long forms (He_Level, Shield_Si410,
    # He_Pressure). LABEL_MAP_NORMALIZE covers both. In_XX legend columns
    # collapse to a zero-padded In_%02d. Anything unknown passes through.
    m = re.match(r"(?i)^in[_\\-\\s]?(\\d{1,2})$", name)
    if m:
        return f"In_{int(m.group(1)):02d}"
    return LABEL_MAP_NORMALIZE.get(name, name)

def parse_minutes(raw_html):
    text = _strip_html_keep_pre(raw_html).replace("\\r\\n", "\\n").replace("\\r", "\\n")
    lines = [ln.strip() for ln in text.split("\\n") if ln.strip()]

    legend = {}
    for ln in lines:
        m = re.match(r"(?i)^\\s*Input\\s+(\\d{1,2})\\s+is\\s+([A-Za-z0-9_]+)\\s*$", ln)
        if m:
            nn = int(m.group(1))
            legend[f"In_{nn:02d}"] = LABEL_MAP_NORMALIZE.get(m.group(2), m.group(2))

    header_idx = header = None
    for i, ln in enumerate(lines):
        parts = _split(ln)
        if parts and parts[0].lower().startswith("date") and len(parts) >= 3:
            norm = [_norm_col(p) for p in parts]
            is_inxx = any(p.startswith("In_") for p in norm)
            labeled = any(p in norm for p in ("HePress", "HeLvl", "H20_Flow", "H2O_Temp", "Shield"))
            if is_inxx or labeled:
                header_idx, header = i, parts
                break
    if header_idx is None:
        raise RuntimeError("Header not found in minute data.")

    colpos = {}
    for idx, name in enumerate(header):
        colpos[_norm_col(name)] = idx

    start = header_idx + 1
    while start < len(lines) and re.fullmatch(r"[-=\\s]+", lines[start]):
        start += 1

    rows, seen = [], set()
    for ln in lines[start:]:
        if ln.lower().startswith("minute data from"):
            continue
        parts = _split(ln)
        if len(parts) < 3:
            continue
        date = parts[colpos.get("Date", 0)] if "Date" in colpos else parts[0]
        time_ = parts[colpos.get("Time", 1)] if "Time" in colpos else (parts[1] if len(parts) > 1 else "")
        key = (date, time_)
        if key in seen:
            continue
        seen.add(key)

        rec = {"Date": date, "Time": time_}
        for k in ALL_NUMERIC:
            rec[k] = None

        labeled_cols_present = any(k in colpos for k in ("HePress", "HeLvl", "H20_Flow", "H2O_Temp", "Shield"))
        if labeled_cols_present:
            for k in ALL_NUMERIC:
                pos = colpos.get(k)
                if pos is not None and pos < len(parts):
                    rec[k] = _to_float(parts[pos])
        else:
            for code in ["CS1", "CDC1", "HT", "HDC", "RF", "FM", "SM", "EC1", "EC2", "EC3", "EC4"]:
                pos = colpos.get(code)
                if pos is not None and pos < len(parts):
                    rec[code] = _to_float(parts[pos])
            for name, pos in colpos.items():
                if name.startswith("In_") and pos < len(parts):
                    lbl = legend.get(name)
                    if lbl and lbl in ALL_NUMERIC:
                        rec[lbl] = _to_float(parts[pos])

        if any(rec[k] is not None for k in ALL_NUMERIC):
            rows.append(rec)

    if not rows:
        raise RuntimeError("Parsed 0 rows.")
    return rows

# ========= FTP fallback (raw .dat file) =========
# The daily .dat file is a fixed, whitespace-separated 34-column layout. These
# 0-indexed positions are ground truth, reconciled field-by-field against the
# HTTP values during a 2026-08 pilot
# He, He-pressure, Shield, ReconRuO, Coldhead and compressor match the HTTP
# values directly. Water flow and temp match too but in DIFFERENT UNITS: the
# .dat reports flow in L/min and temp in degrees C, whereas HTTP (and the rest
# of our data) uses gal/min and degrees F. parse_dat() converts them so an
# FTP-sourced reading is indistinguishable from its HTTP counterpart -- emitting
# the raw .dat numbers would make a healthy unit read like an alarm. Verified on
# live NM1035 data 2026-08-11: .dat 19.017 L / 38.042 C == HTTP 5.024 gal /
# 100.476 F, exactly.
DAT_COL = {
    "Date": 0, "Time": 1, "HeLvl": 3, "H20_Flow": 4, "H2O_Temp": 6, "Shield": 8,
    "ReconRuO": 9, "ReconSi410": 10, "ColdheadRuO": 13, "HePress": 14, "CS1": 21,
}
DAT_MIN_COLS      = 22          # a complete data row has at least this many columns
LITERS_PER_GALLON = 3.785411784 # .dat flow (L/min) -> HTTP flow (gal/min)

def parse_dat(text):
    lines = [ln for ln in text.replace("\\r", "").split("\\n") if ln.strip()]
    # Walk from the end for the last COMPLETE row -- the device may be mid-write
    # on the very last line, leaving it short.
    for ln in reversed(lines):
        parts = ln.split()
        if len(parts) < DAT_MIN_COLS:
            continue
        rec = {}
        for key, idx in DAT_COL.items():
            rec[key] = parts[idx] if key in ("Date", "Time") else _to_float(parts[idx])
        if not (rec.get("Date") and rec.get("Time") and rec.get("HeLvl") is not None):
            continue
        # Align flow/temp with the HTTP unit convention (see note above).
        if rec.get("H20_Flow") is not None:
            rec["H20_Flow"] = rec["H20_Flow"] / LITERS_PER_GALLON
        if rec.get("H2O_Temp") is not None:
            rec["H2O_Temp"] = rec["H2O_Temp"] * 9.0 / 5.0 + 32.0
        # Preserve the raw columns so an FTP-sourced reading stays auditable.
        rec["dat_columns"] = parts
        return rec
    raise RuntimeError("No complete row found in .dat file.")

def _ftp_latest_dat_name(ftp):
    # Only the daily minute files are named dayDDMMYY.dat. Match that pattern
    # EXACTLY and ignore everything else in the directory -- notably
    # rfs_persist.dat, a small device state file that also ends in .dat and is
    # rewritten far more recently than the finalized day files (so any
    # "newest by mtime" pick would grab it by mistake). The name encodes the
    # date authoritatively, so choose the newest by its DDMMYY -> YYMMDD key;
    # this also rides cleanly across the midnight file rollover.
    day = re.compile(r"(?i)^day(\\d{2})(\\d{2})(\\d{2})\\.dat$")
    dated = []
    for n in ftp.nlst():
        m = day.match(n.split("/")[-1])
        if m:
            dd, mm, yy = m.groups()
            dated.append((yy + mm + dd, n.split("/")[-1]))
    if not dated:
        raise RuntimeError("No dayDDMMYY.dat files in FTP mindata dir.")
    return max(dated)[1]

def fetch_latest_ftp_row():
    ftp = ftplib.FTP()
    ftp.connect(MAGMON_HOST, FTP_PORT, timeout=20)
    try:
        ftp.login(FTP_USER, FTP_PASS)
        ftp.cwd(FTP_DIR)
        name = _ftp_latest_dat_name(ftp)
        buf = bytearray()
        ftp.retrbinary("RETR " + name, buf.extend)
    finally:
        try:
            ftp.quit()
        except Exception:
            try:
                ftp.close()
            except Exception:
                pass
    return parse_dat(buf.decode("latin-1", errors="ignore"))

# ========= Timestamps, high-water mark, and reporting =========
# Device Date/Time -> naive datetime. Time is simple (HH:MM[:SS]). The Date
# format varies across the fleet and can be ambiguous (MM/DD vs DD/MM), but that
# does not matter here: within a one-hour fetch the date is constant, so a
# misparse shifts EVERY row by the same amount and cancels out under the Pi-clock
# anchoring in build_samples(). We rely only on Time (for spacing) and on the
# date being stable within the batch. Returns None if unparseable.
_DEV_DATE_FORMATS = ["%m/%d/%y", "%m/%d/%Y", "%Y/%m/%d", "%y/%m/%d",
                     "%d/%m/%y", "%d/%m/%Y", "%m-%d-%y", "%Y-%m-%d", "%d-%m-%y"]
_DEV_TIME_FORMATS = ["%H:%M:%S", "%H:%M"]

def parse_dev_dt(date_str, time_str):
    d = (date_str or "").strip()
    t = (time_str or "").strip()
    if not d or not t:
        return None
    for df in _DEV_DATE_FORMATS:
        for tf in _DEV_TIME_FORMATS:
            try:
                return datetime.datetime.strptime(f"{d} {t}", f"{df} {tf}")
            except ValueError:
                continue
    return None

def floor_minute(dt):
    return dt.replace(second=0, microsecond=0)

def load_hwm():
    for path in HWM_CANDIDATES:
        try:
            with open(path, "r") as fh:
                raw = fh.read().strip()
            if raw:
                return datetime.datetime.fromisoformat(raw)
        except (OSError, ValueError):
            continue
    return None

def save_hwm(dev_dt):
    for path in HWM_CANDIDATES:
        try:
            with open(path, "w") as fh:
                fh.write(dev_dt.isoformat())
            return
        except OSError:
            continue
    print("[nm-magmon-gateway] WARNING: could not persist high-water mark; relying on the DB unique index to dedupe")

def row_to_sample(row, recorded_at_iso):
    # Carry the full parsed row (raw device columns + source tag) for audit and
    # add the lowercase keys report_telemetry_batch reads out of each element.
    s = dict(row)
    s["recorded_at"] = recorded_at_iso
    s["he_lvl"]   = row.get("HeLvl")
    s["he_press"] = row.get("HePress")
    s["h2o_flow"] = row.get("H20_Flow")
    s["h2o_temp"] = row.get("H2O_Temp")
    s["shield"]   = row.get("Shield")
    s["cs1"]      = row.get("CS1")
    return s

def build_samples(rows, hwm):
    # Turn a fetch's rows into the batch to report: only those newer than the
    # high-water mark, each stamped with a Pi-anchored, minute-truncated
    # recorded_at. Anchoring: the Pi keeps accurate NTP time and the embedded
    # MagMon does not, so we trust the Pi for ABSOLUTE placement (newest row ->
    # this minute) and use the device clock only for the RELATIVE spacing between
    # rows. Because offset = now - newest_device_time, any constant misparse of
    # the device date cancels. Returns (samples, newest_device_dt), or
    # (None, None) if no row had a parseable device timestamp.
    dated = []
    for r in rows:
        dt = parse_dev_dt(r.get("Date"), r.get("Time"))
        if dt is not None:
            dated.append((dt, r))
    if not dated:
        return None, None

    uniq = {}
    for dt, r in sorted(dated, key=lambda x: x[0]):
        uniq[dt] = r                       # last write wins; dedupe same-minute rows
    ordered = sorted(uniq.items())         # [(device_dt, row), ...] ascending
    newest = ordered[-1][0]

    now_utc = datetime.datetime.now(datetime.timezone.utc)
    offset = now_utc - newest.replace(tzinfo=datetime.timezone.utc)

    if hwm is None:
        picks = [ordered[-1]]              # forward-only start: just the newest row
    elif newest <= hwm:
        # Device clock reset. These MagMons have no working battery-backed RTC
        # and power on to a fixed epoch (e.g. 13-May-06), so a reboot restarts
        # the device timeline in the "past" -- every row now reads at or behind
        # the high-water mark. Treat it exactly like a fresh start: report the
        # newest row and let main() re-anchor the mark to it, so we recover in
        # ONE cycle instead of going dark for days until the device clock counts
        # back up past the old mark.
        print(f"[nm-magmon-gateway] device clock reset detected (newest {newest.isoformat()} <= mark {hwm.isoformat()}); re-anchoring high-water mark")
        picks = [ordered[-1]]
    else:
        picks = [(dt, r) for dt, r in ordered if dt > hwm]

    samples = []
    for dt, r in picks:
        recorded_at = floor_minute(dt.replace(tzinfo=datetime.timezone.utc) + offset)
        samples.append(row_to_sample(r, recorded_at.isoformat()))
    return samples, newest

def report_batch(samples):
    # Call this after EVERY successful device read, even when samples is empty:
    # report_telemetry_batch stamps last_seen_at (liveness) regardless of whether
    # there was new telemetry, so an idle-but-reachable unit never looks stale.
    payload = {"p_gateway_token": GATEWAY_TOKEN, "p_samples": samples}
    headers = {
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
        "Content-Type": "application/json",
    }
    resp = requests.post(BATCH_REPORT_ENDPOINT, headers=headers, data=json.dumps(payload), timeout=15)
    if resp.status_code >= 300:
        print(f"[nm-magmon-gateway] batch report failed: {resp.status_code} {resp.text}")
        return None
    print(f"[nm-magmon-gateway] reported {len(samples)} sample(s); {resp.text.strip()} newly stored")
    return resp.text.strip()

# ========= Single-instance guard =========
# systemd already guarantees one copy per asset. This flock is a second,
# independent line of defence: even if someone ALSO adds a cron entry by
# mistake, the extra copies take one look at this lock and exit immediately
# instead of piling up. See the "DO NOT SCHEDULE WITH CRON" note at the top.
#
# It is deliberately self-healing about the lock FILE so an in-place upgrade
# (for example switching this service from the old root user to 'pi') can
# never silently take a Pi offline:
#   * If a stale lock file left by an earlier run cannot be opened -- e.g. a
#     root-owned file from the previous version sitting in a sticky /var/lock
#     that 'pi' may not remove -- we try to delete it, and failing that fall
#     back to a lock path this user CAN write. A file-permission problem is
#     NOT the same thing as "another copy is running".
#   * We exit ONLY when flock actually reports the lock is held by a live
#     process. If no lock can be established anywhere, we WARN and keep
#     monitoring rather than going dark -- the lock is a backstop, not a
#     reason to stop reporting telemetry.
LOCK_CANDIDATES = [
    "/var/lock/nm-magmon-gateway-${assetName}.lock",
    "/tmp/nm-magmon-gateway-${assetName}.lock",
]
_LOCK_HANDLE = None
_RUNNING = True

class _AlreadyRunning(Exception):
    pass

def _open_flock(path):
    # Open (creating if needed) and take a non-blocking exclusive lock.
    # Returns an open handle on success, or None if this path is unusable.
    # Raises _AlreadyRunning if the path is fine but a live copy holds the lock.
    try:
        fh = open(path, "a+")
    except OSError:
        # Something is in the way (e.g. a root-owned stale file). Best-effort
        # remove and retry; if we still cannot, this path is out and we move on.
        try:
            os.unlink(path)
            fh = open(path, "a+")
        except OSError as e:
            print(f"[nm-magmon-gateway] lock path unusable: {path} ({e})")
            return None
    try:
        fcntl.flock(fh, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        fh.close()
        raise _AlreadyRunning()
    except OSError as e:
        print(f"[nm-magmon-gateway] cannot lock {path} ({e})")
        fh.close()
        return None
    try:
        fh.seek(0)
        fh.truncate(0)
        fh.write(str(os.getpid()))
        fh.flush()
    except OSError:
        pass  # recording our PID is a nicety, not required for the lock
    return fh

def acquire_singleton_lock():
    global _LOCK_HANDLE
    for path in LOCK_CANDIDATES:
        try:
            fh = _open_flock(path)
        except _AlreadyRunning:
            print("[nm-magmon-gateway] another copy already holds the lock -- exiting so we do not double the poll rate")
            return False
        if fh is not None:
            _LOCK_HANDLE = fh
            return True
    print("[nm-magmon-gateway] WARNING: could not acquire any lock file; continuing without the singleton backstop")
    return True

def handle_shutdown(signum, frame):
    # systemd sends SIGTERM on "systemctl stop" / "restart". Exit between
    # polls rather than mid-request so we never half-report a reading.
    global _RUNNING
    print(f"[nm-magmon-gateway] shutdown signal {signum} received, stopping after this cycle")
    _RUNNING = False

def sleep_interruptible(seconds):
    for _ in range(int(seconds)):
        if not _RUNNING:
            return
        time.sleep(1)

def probe_tcp_connect(host, port, timeout=5):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except Exception as e:
        print(f"[nm-magmon-gateway] TCP connect FAIL -> {host}:{port} ({e})")
        return False

def main():
    signal.signal(signal.SIGTERM, handle_shutdown)
    signal.signal(signal.SIGINT, handle_shutdown)

    print(f"[nm-magmon-gateway] starting for asset '${assetName}' @ {MAGMON_HOST}:{MAGMON_PORT}, polling every ${intervalMinutes} min")

    if not acquire_singleton_lock():
        sys.exit(0)  # Not an error: the other copy is already doing the work.

    hwm = load_hwm()  # newest device timestamp already reported, or None on a fresh start
    if hwm is not None:
        print(f"[nm-magmon-gateway] resuming from high-water mark {hwm.isoformat()}")

    while _RUNNING:
        cycle_started = time.monotonic()
        rows = None

        # Primary path: scrape the HTTP minute table -- the last hour of one-minute
        # rows -- with a few quick retries to ride the webserver's transient
        # connection refusals.
        for attempt in range(1, POLL_RETRIES + 1):
            try:
                if not probe_tcp_connect(MAGMON_HOST, MAGMON_PORT):
                    raise RuntimeError(f"Cannot reach MagMon at {MAGMON_HOST}:{MAGMON_PORT}")
                body = fetch_minutes(num_hours=1, start_day=0, start_hour=1)
                rows = parse_minutes(body)  # ALL rows this cycle, not just the last
                for r in rows:
                    r["source"] = "http"
                break
            except Exception as e:
                print(f"[nm-magmon-gateway] HTTP attempt {attempt}/{POLL_RETRIES} failed: {e}")
                traceback.print_exc()
                # Back off and retry within this cycle unless that was the last
                # attempt or we have been asked to shut down.
                if attempt < POLL_RETRIES and _RUNNING:
                    sleep_interruptible(RETRY_BACKOFF_SECONDS)

        # Fallback path: if HTTP produced nothing (e.g. the GoAhead webserver has
        # wedged), pull the daily .dat over anonymous FTP -- a separate daemon
        # that usually survives an HTTP-server crash. This yields only the single
        # latest row; minutes missed while HTTP is down backfill from the hourly
        # table once HTTP returns.
        if rows is None and _RUNNING:
            try:
                ftp_row = fetch_latest_ftp_row()
                ftp_row["source"] = "ftp"
                rows = [ftp_row]
                print("[nm-magmon-gateway] HTTP unavailable -- got reading via FTP fallback")
            except Exception as e:
                print(f"[nm-magmon-gateway] FTP fallback failed: {e}")
                traceback.print_exc()

        # Report every row newer than the high-water mark. report_batch is called
        # even when there is nothing new (empty list) so liveness still updates.
        if rows:
            try:
                samples, newest = build_samples(rows, hwm)
                if samples is None:
                    # No row carried a parseable device timestamp -- degrade to the
                    # old behaviour: report just the latest row, stamped "now".
                    now_min = floor_minute(datetime.datetime.now(datetime.timezone.utc)).isoformat()
                    report_batch([row_to_sample(rows[-1], now_min)])
                else:
                    report_batch(samples)
                    # Advance the mark on new data, AND re-anchor it downward on a
                    # device clock reset (newest < hwm, handled in build_samples),
                    # so a rebooted MagMon does not stay filtered out. Skip only
                    # when nothing changed (newest == hwm).
                    if newest is not None and newest != hwm:
                        hwm = newest
                        save_hwm(hwm)
            except Exception as e:
                print(f"[nm-magmon-gateway] report failed: {e}")
                traceback.print_exc()

        # Subtract however long the cycle took so the poll rate does not
        # drift later and later over weeks of uptime.
        elapsed = time.monotonic() - cycle_started
        sleep_interruptible(max(1, POLL_INTERVAL_SECONDS - int(elapsed)))

    print("[nm-magmon-gateway] stopped cleanly")

if __name__ == "__main__":
    main()


# --- systemd unit (save as /etc/systemd/system/nm-magmon-gateway-${assetName}.service) ---
# You can also download this as a separate file from the admin panel.
#
# [Unit]
# Description=NM Magnet Monitor gateway reporter -- ${assetName}
# After=network-online.target
# Wants=network-online.target
#
# [Service]
# Type=simple
# ExecStart=/usr/bin/python3 /opt/magmon-gateway-${assetName}.py
# Restart=always
# RestartSec=30
# KillSignal=SIGTERM
# TimeoutStopSec=45
# User=${serviceUser}
# # Unbuffered so "reported OK"/errors reach journald as they happen. Without
# # this, Python block-buffers stdout to the journal pipe and log lines only
# # appear when the buffer fills or the process exits -- which makes a healthy
# # collector look silent and a restart dump a stale backlog.
# Environment=PYTHONUNBUFFERED=1
# StandardOutput=journal
# StandardError=journal
# SyslogIdentifier=magmon-${assetName}
#
# [Install]
# WantedBy=multi-user.target
`;
}

/**
 * The systemd unit for an asset, as a standalone downloadable file.
 *
 * Kept separate from the Python script so the admin panel can hand over both
 * files ready to drop in place. The collector is a long-running daemon, so
 * systemd -- not cron -- is the only supported way to run it: cron would
 * launch an additional copy on every tick while the previous ones keep
 * running. Restart=always also means a Pi that loses power at a customer
 * site comes back on its own.
 */
export function generateSystemdUnit(opts: {
  assetName: string;
  scriptPath?: string;
  serviceUser?: string;
}) {
  const { assetName, serviceUser = "pi" } = opts;
  // Per-asset script path by default so one machine can run several collectors
  // without their units colliding on a shared /opt/magmon-gateway.py.
  const scriptPath = opts.scriptPath ?? `/opt/magmon-gateway-${assetName}.py`;

  return `[Unit]
Description=NM Magnet Monitor gateway reporter -- ${assetName}
Documentation=https://github.com/Sawdizzle/NMMagnetMonitor
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/python3 ${scriptPath}

# Restart forever: a crashed or wedged collector comes back without anyone
# driving to the site. This is the main reason to prefer systemd over cron.
Restart=always
RestartSec=30

# The collector traps SIGTERM and finishes its current cycle before exiting.
KillSignal=SIGTERM
TimeoutStopSec=45

# Runs as an unprivileged user, never root. Group is intentionally omitted so
# systemd uses this user's primary group; set Group= only if you need another.
User=${serviceUser}

# Unbuffered so "reported OK"/errors reach journald as they happen. Without this,
# Python block-buffers stdout to the journal pipe and log lines only surface when
# the buffer fills or the process exits -- making a healthy collector look silent
# and a restart dump a stale backlog of old messages.
Environment=PYTHONUNBUFFERED=1

StandardOutput=journal
StandardError=journal
SyslogIdentifier=magmon-${assetName}

[Install]
WantedBy=multi-user.target
`;
}
