export function generatePiScript(opts: {
  assetName: string;
  gatewayToken: string;
  monitorHost: string;
  monitorPort: number;
  monitorUsername: string;
  monitorPassword: string;
  supabaseUrl: string;
  supabaseAnonKey: string;
  intervalMinutes: number;
}) {
  const {
    assetName,
    gatewayToken,
    monitorHost,
    monitorPort,
    monitorUsername,
    monitorPassword,
    supabaseUrl,
    supabaseAnonKey,
    intervalMinutes,
  } = opts;

  return `#!/usr/bin/env python3
"""
NM Magnet Monitor -- gateway reporting script
Asset: ${assetName}
Generated by the admin panel -- do not commit this file to a public repo,
it contains this asset's gateway token and the MagMon's local credentials.

WHAT THIS DOES
1. Logs into the MagMon's local web interface (HTTP Basic Auth + cookie/form
   login fallback -- these devices are inconsistent about which one they
   want, so this tries Basic Auth first and falls through to a form login
   if the device demands one).
2. Fetches /goform/showMinutesCGI, which returns a <pre>-wrapped text table.
   Two on-the-wire layouts are known to exist across the fleet and this
   parser auto-detects and handles BOTH:
     - "labeled" header, e.g. Date, Time, HeLvl, H20_Flow, H2O_Temp, ...
     - "legend" header, e.g. Date Time In_01 In_02 ... preceded by lines
       like "Input 01 is He_Level" that map generic column names to real
       ones.
   This parsing logic is ported directly from Numed's existing production
   collector scripts (magmon_collect_*.py), not reverse-engineered blind.
3. Takes the most recent row and reports it to Supabase via the
   report_telemetry function, authenticated with this asset's gateway
   token (scoped to only this asset).

SETUP ON THE PI
  sudo apt-get install -y python3-pip
  pip3 install requests --break-system-packages
  sudo nano /etc/systemd/system/nm-magmon-gateway.service   (see bottom of this file)
  sudo systemctl daemon-reload
  sudo systemctl enable --now nm-magmon-gateway
"""

import re
import time
import json
import base64
import socket
import datetime
import traceback
import requests

# --- Fixed per-asset config (do not edit unless re-issued by admin) ---
GATEWAY_TOKEN     = "${gatewayToken}"
SUPABASE_URL      = "${supabaseUrl}"
SUPABASE_ANON_KEY = "${supabaseAnonKey}"

MAGMON_HOST     = "${monitorHost}"
MAGMON_PORT     = ${monitorPort}
MAGMON_USER     = "${monitorUsername}"
MAGMON_PASS     = "${monitorPassword}"
BASE_URL        = f"http://{MAGMON_HOST}:{MAGMON_PORT}"

POLL_INTERVAL_SECONDS = ${intervalMinutes * 60}
REPORT_ENDPOINT = f"{SUPABASE_URL}/rest/v1/rpc/report_telemetry"

SESSION = requests.Session()
SESSION.auth = (MAGMON_USER, MAGMON_PASS)
SESSION.headers.update({
    "User-Agent": "NM-MagMon-Gateway/1.0",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Cache-Control": "no-cache",
})

# ========= Login (only needed if the device rejects Basic Auth alone) =========
LOGIN_ACTION_FALLBACKS = ["/goform/loginCGI", "/goform/ManageLogin", "/goform/login", "/goform/formLogin", "/cgi-bin/login"]
USER_FIELD_CANDIDATES  = ["username", "user", "login", "uname", "name"]
PASS_FIELD_CANDIDATES  = ["password", "pass", "pwd", "key"]

def discover_login_form(html, page_url):
    m_action = re.search(r'(?is)<form[^>]*action=["\\']([^"\\']+)["\\']', html)
    action_url = requests.compat.urljoin(page_url, m_action.group(1)) if m_action else None
    names = re.findall(r'(?is)<input[^>]*name=["\\']([^"\\']+)["\\'][^>]*>', html)
    user_field = pass_field = None
    for nm in names:
        if user_field is None and re.search(r'(user|login|name|uname)', nm, re.I):
            user_field = nm
        if pass_field is None and re.search(r'(pass|pwd|key)', nm, re.I):
            pass_field = nm
    return action_url, user_field or USER_FIELD_CANDIDATES[0], pass_field or PASS_FIELD_CANDIDATES[0]

def try_login(action_url, user_field, pass_field, referer_url):
    if not action_url:
        raise RuntimeError("No login action URL discovered.")
    form = {user_field: MAGMON_USER, pass_field: MAGMON_PASS}
    resp = SESSION.post(action_url, data=form, headers={"Referer": referer_url}, timeout=12)
    if re.search(r"Unknown Username/Password|User not logged in|Access Error", resp.text, re.I):
        raise RuntimeError("Login POST returned failure.")

def login_magmon():
    html, page_used = None, BASE_URL + "/"
    for url in [f"{BASE_URL}/index.html", f"{BASE_URL}/", f"{BASE_URL}/login.html"]:
        try:
            resp = SESSION.get(url, timeout=10)
            html, page_used = resp.text, url
            break
        except Exception:
            continue

    if html:
        try:
            action_url, user_field, pass_field = discover_login_form(html, page_used)
            if action_url:
                try_login(action_url, user_field, pass_field, page_used)
                return
        except Exception:
            pass

    for rel in LOGIN_ACTION_FALLBACKS:
        url = requests.compat.urljoin(BASE_URL, rel)
        for uf in USER_FIELD_CANDIDATES:
            for pf in PASS_FIELD_CANDIDATES:
                try:
                    try_login(url, uf, pf, page_used)
                    return
                except Exception:
                    continue
    raise RuntimeError("All login attempts failed.")

def fetch_minutes_raw_socket(num_hours=1, start_day=0, start_hour=1):
    # Some MagMon units return a response urllib3/http.client can't parse
    # as standard HTTP (BadStatusLine). Numed's production scripts hit this
    # too and work around it with a raw socket request instead.
    path = f"/goform/showMinutesCGI?num_hours={num_hours}&start_day={start_day}&start_hour={start_hour}"
    basic = base64.b64encode(f"{MAGMON_USER}:{MAGMON_PASS}".encode("ascii")).decode("ascii")
    cookie_parts = [f"{c.name}={c.value}" for c in SESSION.cookies]
    req_lines = [
        f"GET {path} HTTP/1.0",
        f"Host: {MAGMON_HOST}:{MAGMON_PORT}",
        f"Authorization: Basic {basic}",
        "User-Agent: NM-MagMon-Gateway/1.0",
        "Accept: */*",
    ]
    if cookie_parts:
        req_lines.append("Cookie: " + "; ".join(cookie_parts))
    req_lines.append("")
    req_lines.append("")
    req_bytes = "\\r\\n".join(req_lines).encode("ascii", errors="ignore")

    chunks = []
    with socket.create_connection((MAGMON_HOST, MAGMON_PORT), timeout=15) as s:
        s.sendall(req_bytes)
        while True:
            data = s.recv(4096)
            if not data:
                break
            chunks.append(data)
    body_all = b"".join(chunks).decode("latin-1", errors="ignore")
    return re.split(r"\\r?\\n\\r?\\n", body_all, maxsplit=1)[-1]

def fetch_minutes(num_hours=1, start_day=0, start_hour=1):
    url = f"{BASE_URL}/goform/showMinutesCGI?num_hours={num_hours}&start_day={start_day}&start_hour={start_hour}"
    try:
        resp = SESSION.get(url, timeout=20)
        body = resp.text
    except Exception as e:
        print(f"[nm-magmon-gateway] normal fetch failed ({e}); trying raw socket fallback")
        body = fetch_minutes_raw_socket(num_hours, start_day, start_hour)

    if "User not logged in" in body or "Access Error" in body:
        login_magmon()
        try:
            resp = SESSION.get(url, timeout=20)
            body = resp.text
        except Exception:
            body = fetch_minutes_raw_socket(num_hours, start_day, start_hour)
        if "User not logged in" in body or "Access Error" in body:
            raise RuntimeError("Still not logged in after login attempt.")
    return body

# ========= Parser (ported from Numed's production magmon_collect_*.py) =========
LABEL_MAP_NORMALIZE = {
    "He_Level": "HeLvl", "HeLevel": "HeLvl", "Helium_Level": "HeLvl", "HeLvl": "HeLvl",
    "Water_Flow": "H20_Flow", "WaterFlow": "H20_Flow", "H20_Flow": "H20_Flow",
    "Water_Temp": "H2O_Temp", "WaterTemp": "H2O_Temp", "Water_Temperature": "H2O_Temp", "H2O_Temp": "H2O_Temp",
    "Shield_Si410": "Shield", "Shield": "Shield",
    "Recon_RuO": "ReconRuO", "ReconRuO": "ReconRuO",
    "Recon_Si410": "ReconSi410", "ReconSi410": "ReconSi410",
    "Coldhead_RuO": "ColdheadRuO", "ColdheadRuO": "ColdheadRuO",
    "He_Pressure": "HePress", "He_Press": "HePress", "HePress": "HePress",
}
ALL_NUMERIC = ["HeLvl", "H20_Flow", "H2O_Temp", "Shield", "ReconRuO", "ReconSi410", "ColdheadRuO",
               "HePress", "CS1", "CDC1", "HT", "HDC", "RF", "FM", "SM", "EC1", "EC2", "EC3", "EC4"]

def _to_float(x):
    try:
        return float(str(x).strip())
    except Exception:
        return None

def _strip_html_keep_pre(text):
    m = re.search(r"(?is)<pre[^>]*>(.*?)</pre>", text)
    content = m.group(1) if m else text
    return re.sub(r"(?is)<[^>]+>", "", content)

def _split(line):
    if "," in line:
        return [c.strip() for c in line.split(",")]
    return re.split(r"[ \\t]+", line.strip())

def parse_minutes(raw_html):
    text = _strip_html_keep_pre(raw_html).replace("\\r\\n", "\\n").replace("\\r", "\\n")
    lines = [ln.strip() for ln in text.split("\\n") if ln.strip()]

    legend = {}
    for ln in lines:
        m = re.match(r"(?i)^\\s*Input\\s+(\\d{1,2})\\s+is\\s+([A-Za-z0-9_]+)\\s*$", ln)
        if m:
            nn = int(m.group(1))
            legend[f"In_{nn:02d}"] = LABEL_MAP_NORMALIZE.get(m.group(2), m.group(2))

    header_idx = header = None
    for i, ln in enumerate(lines):
        parts = _split(ln)
        if parts and parts[0].lower().startswith("date") and len(parts) >= 3:
            is_inxx = any(re.match(r"(?i)^in[_\\-\\s]?\\d{1,2}$", p) for p in parts)
            labeled = any(p in parts for p in ("HePress", "HeLvl", "H20_Flow", "H2O_Temp", "Shield"))
            if is_inxx or labeled:
                header_idx, header = i, parts
                break
    if header_idx is None:
        raise RuntimeError("Header not found in minute data.")

    colpos = {}
    for idx, name in enumerate(header):
        name_std = name
        if name_std.lower().startswith("in"):
            m = re.match(r"(?i)^in[_\\-\\s]?(\\d{1,2})$", name_std)
            if m:
                name_std = f"In_{int(m.group(1)):02d}"
        colpos[name_std] = idx

    start = header_idx + 1
    while start < len(lines) and re.fullmatch(r"[-=\\s]+", lines[start]):
        start += 1

    rows, seen = [], set()
    for ln in lines[start:]:
        if ln.lower().startswith("minute data from"):
            continue
        parts = _split(ln)
        if len(parts) < 3:
            continue
        date = parts[colpos.get("Date", 0)] if "Date" in colpos else parts[0]
        time_ = parts[colpos.get("Time", 1)] if "Time" in colpos else (parts[1] if len(parts) > 1 else "")
        key = (date, time_)
        if key in seen:
            continue
        seen.add(key)

        rec = {"Date": date, "Time": time_}
        for k in ALL_NUMERIC:
            rec[k] = None

        labeled_cols_present = any(k in colpos for k in ("HePress", "HeLvl", "H20_Flow", "H2O_Temp", "Shield"))
        if labeled_cols_present:
            for k in ALL_NUMERIC:
                pos = colpos.get(k)
                if pos is not None and pos < len(parts):
                    rec[k] = _to_float(parts[pos])
        else:
            for code in ["CS1", "CDC1", "HT", "HDC", "RF", "FM", "SM", "EC1", "EC2", "EC3", "EC4"]:
                pos = colpos.get(code)
                if pos is not None and pos < len(parts):
                    rec[code] = _to_float(parts[pos])
            for name, pos in colpos.items():
                if name.startswith("In_") and pos < len(parts):
                    lbl = legend.get(name)
                    if lbl and lbl in ALL_NUMERIC:
                        rec[lbl] = _to_float(parts[pos])

        if any(rec[k] is not None for k in ALL_NUMERIC):
            rows.append(rec)

    if not rows:
        raise RuntimeError("Parsed 0 rows.")
    return rows

# ========= Report to Supabase =========
def report(row):
    # Timestamp using THIS machine's clock (the Pi), not the MagMon's.
    # The Pi is a normal Linux box with internet access and keeps
    # accurate time via NTP; the embedded MagMon controller does not.
    recorded_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
    payload = {
        "p_gateway_token": GATEWAY_TOKEN,
        "p_recorded_at": recorded_at,
        "p_he_lvl": row.get("HeLvl"),
        "p_he_press": row.get("HePress"),
        "p_h2o_flow": row.get("H20_Flow"),
        "p_h2o_temp": row.get("H2O_Temp"),
        "p_shield": row.get("Shield"),
        "p_cs1": row.get("CS1"),
        "p_raw": row,
    }
    headers = {
        "apikey": SUPABASE_ANON_KEY,
        "Authorization": f"Bearer {SUPABASE_ANON_KEY}",
        "Content-Type": "application/json",
    }
    resp = requests.post(REPORT_ENDPOINT, headers=headers, data=json.dumps(payload), timeout=10)
    if resp.status_code >= 300:
        print(f"[nm-magmon-gateway] report failed: {resp.status_code} {resp.text}")
    else:
        print(f"[nm-magmon-gateway] reported OK: {row['Date']} {row['Time']}")

def probe_tcp_connect(host, port, timeout=5):
    try:
        with socket.create_connection((host, port), timeout=timeout):
            return True
    except Exception as e:
        print(f"[nm-magmon-gateway] TCP connect FAIL -> {host}:{port} ({e})")
        return False

def main():
    print(f"[nm-magmon-gateway] starting for asset '${assetName}' @ {MAGMON_HOST}:{MAGMON_PORT}, polling every ${intervalMinutes} min")
    while True:
        try:
            if not probe_tcp_connect(MAGMON_HOST, MAGMON_PORT):
                raise RuntimeError(f"Cannot reach MagMon at {MAGMON_HOST}:{MAGMON_PORT}")
            body = fetch_minutes(num_hours=1, start_day=0, start_hour=1)
            rows = parse_minutes(body)
            report(rows[-1])  # most recent row
        except Exception as e:
            print(f"[nm-magmon-gateway] error: {e}")
            traceback.print_exc()
        time.sleep(POLL_INTERVAL_SECONDS)

if __name__ == "__main__":
    main()


# --- systemd unit (save as /etc/systemd/system/nm-magmon-gateway.service) ---
#
# [Unit]
# Description=NM Magnet Monitor gateway reporter -- ${assetName}
# After=network-online.target
# Wants=network-online.target
#
# [Service]
# ExecStart=/usr/bin/python3 /home/pi/nm-magmon-gateway.py
# Restart=always
# RestartSec=10
# User=pi
#
# [Install]
# WantedBy=multi-user.target
`;
}
